language: node_js
node_js:
- stable
jobs:
  include:
  - stage: offhook
    deploy:
      provider: lambda
      function_name: "state-event-offhook"
      region: "us-east-1"
      role: $AWS_ROLE
      runtime: "nodejs6.10"
      handler_name: "offhook"
      environment_variables:
        - AWS_LAMBDA_ACCESS_KEY_ID=$AWS_LAMBDA_ACCESS_KEY_ID
        - AWS_LAMBDA_SECRET_ACCESS_KEY=$AWS_LAMBDA_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME=$S3_BUCKET_NAME
      on:
        branch: master
  - stage: dial
    deploy:
      provider: lambda
      function_name: "state-event-dial"
      region: "us-east-1"
      role: $AWS_ROLE
      runtime: "nodejs6.10"
      handler_name: "dial"
      environment_variables:
        - AWS_LAMBDA_ACCESS_KEY_ID=$AWS_LAMBDA_ACCESS_KEY_ID
        - AWS_LAMBDA_SECRET_ACCESS_KEY=$AWS_LAMBDA_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME=$S3_BUCKET_NAME
      on:
        branch: master
  - stage: connected
    deploy:
      provider: lambda
      function_name: "state-event-connected"
      region: "us-east-1"
      role: $AWS_ROLE
      runtime: "nodejs6.10"
      handler_name: "connected"
      environment_variables:
        - AWS_LAMBDA_ACCESS_KEY_ID=$AWS_LAMBDA_ACCESS_KEY_ID
        - AWS_LAMBDA_SECRET_ACCESS_KEY=$AWS_LAMBDA_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME=$S3_BUCKET_NAME
      on:
        branch: master
  - stage: hangup
    deploy:
      provider: lambda
      function_name: "state-event-hangup"
      region: "us-east-1"
      role: $AWS_ROLE
      runtime: "nodejs6.10"
      handler_name: "hangup"
      environment_variables:
        - AWS_LAMBDA_ACCESS_KEY_ID=$AWS_LAMBDA_ACCESS_KEY_ID
        - AWS_LAMBDA_SECRET_ACCESS_KEY=$AWS_LAMBDA_SECRET_ACCESS_KEY
        - S3_BUCKET_NAME=$S3_BUCKET_NAME
      on:
        branch: master
